"""Package configuration for ABI-CDMs."""

from setuptools import setup, find_packages

setup(
    name="abi-cdms",
    version="1.1.0",
    description="Amortized Bayesian inference of conflict diffusion models",
    author="Wanke Pan",
    author_email="panwanke2023@gmail.com",
    url="https://github.com/Chuan-Peng-Lab/ABI-CDMs",
    license="AGPL-3.0-or-later",
    packages=find_packages(),
    python_requires=">=3.10",
    install_requires=[
        "numpy>=1.26",
        "pandas>=2.0",
        "scipy>=1.10",
        "bayesflow~=2.0.7",
        "torch>=2.0",
        "keras>=3.0",
        "arviz>=0.18",
        "xarray>=2023.0",
        "numba>=0.58",
        "numba-stats>=1.7",
        "matplotlib>=3.7",
        "seaborn>=0.12",
        "scikit-learn>=1.3",
        "joblib>=1.3",
        "rsatoolbox>=0.3",
        "umap-learn>=0.5",
        "statsmodels>=0.14",
        "pingouin>=0.5",
        "bambi>=0.13",
        "tqdm>=4.65",
        "fastkde>=1.0",
        "tables>=3.8",
    ],
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Science/Research",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Scientific/Engineering :: Psychology",
    ],
)
